name = "news-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "news_db"
database_name = "news-db"
database_id = "20478c51-9784-4d67-8bb4-653eed21c7c0"

[[kv_namespaces]]
binding = "news_cache"
id = "9cdd243a0086407cabb3c39f8dbb0be7"

[triggers]
crons = ["0 * * * *"]